name: TCC2
channels:
- conda-forge
- defaults
- anaconda
dependencies:
- python=3.6
- jupyter=1.0.0
- matplotlib=3.1.1
- pandas=0.25.1
- scipy=1.3.1
- seaborn=0.9.0
- altair=4.1.0
- bokeh==2.0.1
- vega
- numpy==1.16.*
- descartes=1.1.0
- geopandas==0.7.0
- shapely==1.7.0
- pyproj==2.6.0
- seaborn==0.10.0
- sklearn==0.22.2
- scipy==1.2.3
- parfit==0.220
- xgboost==1.1.0
